import Foundation

/// Runtime's command option policy, shared by validation and the SDK catalog.
internal enum GatewayCommandFlagInventory {
  static let allowedOptions: [String: Set<String>] = [
    "document get": ["document-id", "include-tabs-content", "suggestions-view-mode", "dry-run"],
    "document create": ["title", "json", "json-file", "dry-run"],
    "document batch-update": ["document-id", "text", "json", "json-file", "dry-run"],
    "spreadsheet get": ["spreadsheet-id", "dry-run"],
    "spreadsheet get-by-data-filter": ["spreadsheet-id", "input-file", "dry-run"],
    "spreadsheet create": ["title", "dry-run"],
    "spreadsheet batch-update": ["spreadsheet-id", "confirm-spreadsheet-id", "input-file", "dry-run"],
    "sheet copy-to": ["spreadsheet-id", "sheet-id", "destination-spreadsheet-id", "dry-run"],
    "values get": ["spreadsheet-id", "range", "dry-run"],
    "values batch-get": ["spreadsheet-id", "range", "dry-run"],
    "values batch-get-by-data-filter": ["spreadsheet-id", "input-file", "dry-run"],
    "developer-metadata get": ["spreadsheet-id", "metadata-id", "dry-run"],
    "developer-metadata search": ["spreadsheet-id", "input-file", "dry-run"],
    "values append": ["spreadsheet-id", "range", "values", "json-values", "input-file", "major-dimension", "value-input-option", "dry-run"],
    "values update": ["spreadsheet-id", "range", "values", "json-values", "input-file", "major-dimension", "value-input-option", "dry-run"],
    "values clear": ["spreadsheet-id", "range", "confirm-range", "dry-run"],
    "values batch-update": ["spreadsheet-id", "input-file", "value-input-option", "dry-run"],
    "values batch-clear": ["spreadsheet-id", "input-file", "confirm-clear", "dry-run"],
    "values batch-clear-by-data-filter": ["spreadsheet-id", "input-file", "confirm-clear", "dry-run"],
    "values batch-update-by-data-filter": ["spreadsheet-id", "input-file", "value-input-option", "dry-run"],
    "about get": ["dry-run"], "changes start-token": ["drive-id", "dry-run"],
    "changes list": ["page-token", "page-size", "page-all", "max-pages", "drive-id", "dry-run"],
    "shared-drives list": ["query", "page-size", "page-token", "page-all", "max-pages", "dry-run"],
    "shared-drives get": ["drive-id", "dry-run"],
    "files list": ["query", "page-size", "page-token", "page-all", "max-pages", "drive-id", "dry-run"],
    "files get": ["file-id", "dry-run"],
    "files download": ["file-id", "output", "max-bytes", "overwrite", "dry-run"],
    "files export": ["file-id", "mime-type", "output", "max-bytes", "overwrite", "dry-run"],
    "permissions list": ["file-id", "page-size", "page-token", "page-all", "max-pages", "dry-run"],
    "permissions get": ["file-id", "permission-id", "dry-run"],
    "comments list": ["file-id", "page-size", "page-token", "page-all", "max-pages", "dry-run"],
    "comments get": ["file-id", "comment-id", "dry-run"],
    "replies list": ["file-id", "comment-id", "page-size", "page-token", "page-all", "max-pages", "dry-run"],
    "replies get": ["file-id", "comment-id", "reply-id", "dry-run"],
    "revisions list": ["file-id", "page-size", "page-token", "page-all", "max-pages", "dry-run"],
    "revisions get": ["file-id", "revision-id", "dry-run"],
    "revisions download": ["file-id", "revision-id", "output", "max-bytes", "overwrite", "dry-run"],
    "folders create": ["name", "parent-id", "dry-run"],
    "files upload": ["input", "max-bytes", "name", "parent-id", "mime-type", "dry-run"],
    "files copy": ["file-id", "confirm-file-id", "name", "parent-id", "dry-run"],
    "files replace-content": ["file-id", "confirm-file-id", "expected-modified-time", "input", "max-bytes", "dry-run"],
    "files rename": ["file-id", "confirm-file-id", "expected-modified-time", "name", "dry-run"],
    "files move": ["file-id", "confirm-file-id", "expected-modified-time", "add-parents", "remove-parents", "dry-run"],
    "files trash": ["file-id", "confirm-file-id", "expected-modified-time", "dry-run"],
    "files untrash": ["file-id", "confirm-file-id", "expected-modified-time", "dry-run"],
    "files delete": ["file-id", "confirm-file-id", "expected-modified-time", "acknowledge-permanent-delete", "dry-run"],
    "permissions create": ["file-id", "type", "role", "email", "domain", "acknowledge-broad-access", "dry-run"],
    "permissions update": ["file-id", "permission-id", "confirm-permission-id", "expected-role", "role", "dry-run"],
    "permissions delete": ["file-id", "permission-id", "confirm-permission-id", "expected-role", "dry-run"],
    "comments create": ["file-id", "content", "dry-run"],
    "comments update": ["file-id", "comment-id", "confirm-comment-id", "content", "dry-run"],
    "comments delete": ["file-id", "comment-id", "confirm-comment-id", "dry-run"],
    "replies create": ["file-id", "comment-id", "content", "action", "dry-run"],
    "replies update": ["file-id", "comment-id", "reply-id", "confirm-reply-id", "content", "dry-run"],
    "replies delete": ["file-id", "comment-id", "reply-id", "confirm-reply-id", "dry-run"],
    "revisions update": ["file-id", "revision-id", "confirm-revision-id", "keep-forever", "publish", "dry-run"]
  ]
}
